/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppLogos: typeof import('./src/components/AppLogos.vue')['default']
    InputEntry: typeof import('./src/components/InputEntry.vue')['default']
    UvButton: typeof import('@climblee/uv-ui/components/uv-button/uv-button.vue')['default']
    UvIcon: typeof import('@climblee/uv-ui/components/uv-icon/uv-icon.vue')['default']
    UvInput: typeof import('@climblee/uv-ui/components/uv-input/uv-input.vue')['default']
    UvLoadingIcon: typeof import('@climblee/uv-ui/components/uv-loading-icon/uv-loading-icon.vue')['default']
    UvOverlay: typeof import('@climblee/uv-ui/components/uv-overlay/uv-overlay.vue')['default']
    UvPopup: typeof import('@climblee/uv-ui/components/uv-popup/uv-popup.vue')['default']
    UvSafeBottom: typeof import('@climblee/uv-ui/components/uv-safe-bottom/uv-safe-bottom.vue')['default']
    UvSkeletons: typeof import('@climblee/uv-ui/components/uv-skeletons/uv-skeletons.vue')['default']
    UvStatusBar: typeof import('@climblee/uv-ui/components/uv-status-bar/uv-status-bar.vue')['default']
    UvTransition: typeof import('@climblee/uv-ui/components/uv-transition/uv-transition.vue')['default']
  }
}
